### ISSUE TITLE
User can create an account

### ISSUE THREAD

**Issue by tran-christopher** [tran-christopher/Mexel#1]
## ⚙️ Feature

User can create an account

## 📐 Functionality

User can sign up for an account. Once signed up user can use their credentials to sign back in and sign back out.

## ✅ Task Lists

> ##### Commit checklists for tasks needed to complete the feature.

### ☁️ Server Tasks

- [x] Add a post method that will take the inputted username and password and insert them into the database when a user signs up
- [x] Add a get method that will take the inputted username and password and retrieve them from the database when a user signs in
- [x] Test with HTTPie
- [x] Handle all errors and respond to the client

### ⚡ Client Tasks

- [x] Create Sign Up page component
- [x] Create Sign In page component 
- [x] Wrap components in a form element 
- [x] Pass in a handleSubmit function for each one to call the API with the user inputted data.

### 🧑‍⚕️ Clean Up Tasks

- [x] Identify possible edge cases and handle accordingly.
- [x] Implement/complete CSS/styling
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Remove all unnecessary console logs.
- [x] Remove all commented out code (not comments).
- [x] Code clean up (repetition, naming etc).
- [x] Ensure all added functionality works as intended one more time!
