### ISSUE TITLE
User can render a video link to be viewed (formerly user can convert)

### ISSUE THREAD

**Issue by tran-christopher** [tran-christopher/Mexel#2]
## ⚙️ Feature

User can convert a youtube link to an mp3 file

## 📐 Functionality

User can paste and submit a  youtube video link, converting it to an audio file and giving the user the option to have it saved to their account. 

## ✅ Task Lists

> ##### Commit checklists for tasks needed to complete the feature.

### ☁️ Server Tasks

- [x] Add a post method that adds a song to the "Songs" table if the user wants to save it
- [x] Handle all errors and respond to the client

### ⚡ Client Tasks

- [x] Create left static component
- [x] Create component for landing page, youtube link input page and saved songs page
- [x] Wrap youtube link input page in <form> element
- [x] Pass in a handleSubmit function to call the API when the user submits a link
- [x] Embed an a video player that displays video when url is submitted
- [x] When the API is called and the video plays in the embedded player, the user can play/pause/reset as much as they want. 
- [x] The user is given a prompt to save the url if they want 

### 🧑‍⚕️ Clean Up Tasks

- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Remove all unnecessary console logs.
- [x] Remove all commented out code (not comments).
- [x] Ensure all added functionality works as intended one more time!
