### ISSUE TITLE
User can create a playlist and add new videos to it

### ISSUE THREAD

**Issue by tran-christopher** [tran-christopher/Mexel#5]
## ⚙️ Feature

User can create a playlist 

## 📐 Functionality

User will be able to insert the name of their new playlist into an input and save it. Once saved, users will be able to go to their saved videos list and have an option to sort to their playlist.

## ✅ Task Lists

> ##### Commit checklists for tasks needed to complete the feature.

### ☁️ Server Tasks

- [x] Add post method that will take the inputted playlist name and userId of user and insert into "Playlists" table 
- [x] Add post method that will display all created playlists from database when playlist tab is clicked 
- [x] Add post method that will insert a video into "PlaylistSongs" table when user wants to add a video into a playlist
- [x] Test with HTTPie
- [x] Handle all errors and respond to the client

### ⚡ Client Tasks

- [x] Create playlist input component 
- [x] Create saved playlists component
- [x] Complete playlist input component that once user submits playlist name an appropriate API call is made to insert into database
- [x] Complete saved playlists component that once user clicks on corresponding tab an API call is made to retrieve all saved playlists for that user from database
